spring:
  datasource:
    url: jdbc:mysql://203.195.217.161:3306/idea_demo?useUnicode=true&characterEncoding=UTF-8
    hikari:
      #>=8.0:com.mysql.cj.jdbc.Driver
      #<=8.0:com.mysql.jdbc.Driver
      username: root
      password: 199851025
      driver-class-name:  com.mysql.cj.jdbc.Driver
      maximum-pool-size: 10
      max-lifetime: 10000
  application:
    name: user-center
  cloud:
    nacos:
      discovery:
        server-addr: 203.195.217.161:8848
        namespace: ZGQ8164ac1f-9263-4bdc-99be-5d84be729842
        metadata:
          xxx: 33343536
          heol: hehe
          #设置集群名
        cluster-name: JX

server:
  port: 8074

